# Generated by Django 4.0.7 on 2022-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Цена в рублях'),
        ),
    ]
