# Generated by Django 4.0.7 on 2022-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_options_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitForMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название месяца')),
                ('profit', models.IntegerField(default=0, verbose_name='Прибыль за месяц')),
                ('date', models.DateField(default=None, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена в рублях'),
        ),
    ]
