# Generated by Django 4.0.7 on 2022-09-21 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profitformonth_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название работы')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('date', models.DateField(default=datetime.date(2022, 9, 21), verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'MyWork',
                'verbose_name_plural': 'MyWorks',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='profitformonth',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'ProfitForMonth', 'verbose_name_plural': 'ProfitForMonths'},
        ),
    ]
